Traceback (most recent call last):
  File "init": in "boot" , at line 354
  File "init": in "execfile" , at line 309
  File "tm2c.py": in "#main" , at line 301
  File "tm2c.py": in "tm2c" , at line 251
  File "tm2c.py": in "do_block" , at line 116
Exception:
  keyError "second"
